Feat: added add product in wishlisst , move to cart , delete item from…
Divya70/E-Commerce-App pull request #5
Opened 2022-04-02 11:28 UTC by Divya70

added product in wishlist
**add to wishlist**
**move to cart**
**remove from wishlist**

2022-04-02 12:59 UTC, Abhijeet43 requested changes
- When Items are moved from cart to wishlist... If the item already exists in wishlist then we end up with two wishlist cards of  a same item
- Bug video : https://www.awesomescreenshot.com/video/8199568?key=d2bf25342598c6677d6f99bc1541d013

2022-04-04 16:23 UTC, Ayushi20-19 approved these changes
Above Suggested changes else looks good to merge

2022-04-04 16:23 UTC, Ayushi20-19 commented on src/components/Products/Products.js
> +  const token = localStorage.getItem("token");
You have auth token in context so avoid using local storage

2022-04-04 16:33 UTC, Divya70 commented
yes , i will make changes in next pr

2022-04-04 16:34 UTC, Divya70 commented on src/components/Products/Products.js
> +  const token = localStorage.getItem("token");
okay, i will change that in next pr

2022-04-04 16:57 UTC, Meghana-sk commented
- Suggested few changes regarding imports and usage of console logs
- Consider fixing a bug in upcoming PRs: If wishlisted item A is there on wishlist page and the same item A is there on cart page and it is moved to wishlist, 2 same items get added. - @Abhijeet43 good observation.
- Good job @Divya70 :)

2022-04-04 16:57 UTC, Meghana-sk approved these changes

2022-04-04 16:57 UTC, Meghana-sk commented on src/components/Products/Products.js
>        console.log("error");
Suggestions: Console logs can be avoided. It can be used while development for testing purposes

2022-04-04 16:57 UTC, Meghana-sk commented on src/pages/Signup/Signup.js
>  import { useAuth } from "../../Context/Auth-Context";
Suggestion: All user defined hooks can be imported after pre defined hooks

2022-04-04 17:01 UTC, merged